### ISSUE TITLE
Question about simcoal

### ISSUE THREAD

**Issue by smhoban** [christianparobek/skeleSim#33]
I was working through a case study of a 'bottleneck' using the coalescent option in skelesim.  Normally I'd use a positive growth rate (growth rate going into the past), but I realized you can't make an event to have that growth stop (no option to create an event aside from merging populations).  So what happens if you tell simcoal to have a growth rate but that doesn't stop?  Will simcoal break?  I would think so but not sure.  Just wondering has anyone played with skelesim and growth rates yet.

**Comment by EricArcher** [comment]
Sean, I've actually never done simcoal runs using growth rates. The few times I've played with bottlenecks, I've used historical events to specify new population sizes (instantaneous growth). The source and sink demes are the same and you can enter population sizes ("new.size") as a proportion of the size preceding (later in time).

You can make an event to set the new growth rate though. It is the sixth value in the historical events matrix.

**Comment by smhoban** [comment]
Ok.  I don't think this is possible in Skelesim right now either right?  It looks like you can just change coalescent times and it shows the historical event but doesn't let you manually edit the historical event (which does help ensure people don't put in crazy numbers..)

**Comment by smhoban** [comment]
Continuing this theme of growth rates.  We currently have a tab for 'growth rates,' but the 'vector of growth rates' does not seem to be editable- I can't type any numbers in there.  Is this an error or is it just a tab that hasn't been worked on yet?

**Comment by stranda** [comment]
Ok, I've updated the shiny interface to allow
1) entering histories as a matrix (and the ability to add new rows to the matrix).  This real-time updates the population history graph and changes using the mouse on the population history graph are reflected in the matrix.  This should allow one to specify bottlenecks, growth through time, and different migration matrices (number them starting at zero), for example.

2) Speaking of migration matrices, you can now enter any number of them for a particular scenario.  If everything is working like the code suggests, this should now work in fastsimcoal (though there are some issues Eric and I are still working out).  Rmetasim still only uses the first matrix.  Working on that now....

Hopefully this addresses this issue and as a result, I'm closing.  If there are additional bugs introduced because of this change, I say open a new issue
