### ISSUE TITLE
markdown dependency on windows

### ISSUE THREAD

**Issue by christianparobek** [christianparobek/skeleSim#55]
After fixing the `shinyFiles` dependency problem, Ubuntu machines ran just fine, but Windows ran into another problem: `package markdown not found`.

**Comment by christianparobek** [comment]
So I added `markdown` to the Depends list of DESCRIPTION. Seems to fix the issue on the Windows computer.

**Comment by EricArcher** [comment]
Does anyone know where in the package `markdown` is getting used and what functions are being used there?

We get the following two NOTEs on package Check:

```
checking package dependencies ... NOTE
Depends: includes the non-default packages:
  ‘strataG’ ‘rmetasim’ ‘shiny’ ‘shinyFiles’ ‘markdown’ ‘ggplot2’
Adding so many packages to the search path is excessive and importing
selectively is preferable.

checking dependencies in R code ... NOTE
Packages in Depends field not imported from:
  ‘markdown’ ‘shinyFiles’
  These packages need to be imported from (in the NAMESPACE file)
  for when this namespace is loaded but not attached.
```

CRAN submission will balk at this NOTE, so I'm wondering if we can move it and/or shinyFiles from Depends to Imports by adding @importFrom in some documentation.

**Comment by stranda** [comment]
The markdown package provides an includeMarkdown() function that allows
easy creation of help text in the shiny app.  shinyFiles implements all of
the file dialogs.

Indeed, most if not all  of the depends in the skeleSim DESCRIPTION file
are there because the shiny app does not share a namespace with the
skeleSim package.  This forces them to be loaded into the environment that
skeleSimGUI() executes in.

I can easily set up a series of library() calls that run when the
skeleSimGUI() is executed.  I would like to make sure that they are
installed when the package is installed, however.  Right now the depends
structure handles that.  Can they just be moved to imports, even if they
are not showing up in the NAMESPACE file?  We could also move them to
"suggests" but my understanding is that, by definition, these are not
necessarily installed during package installation.

cheers,
a.

On Tue, May 24, 2016 at 5:42 PM, Eric Archer notifications@github.com
wrote:

> Does anyone know where in the package markdown is getting used and what
> functions are being used there?
> 
> We get the following two NOTEs on package Check:
> 
> checking package dependencies ... NOTE
> Depends: includes the non-default packages:
>   ‘strataG’ ‘rmetasim’ ‘shiny’ ‘shinyFiles’ ‘markdown’ ‘ggplot2’
> Adding so many packages to the search path is excessive and importing
> selectively is preferable.
> 
> checking dependencies in R code ... NOTE
> Packages in Depends field not imported from:
>   ‘markdown’ ‘shinyFiles’
>   These packages need to be imported from (in the NAMESPACE file)
>   for when this namespace is loaded but not attached.
> 
> CRAN submission will balk at this NOTE, so I'm wondering if we can move it
> and/or shinyFiles from Depends to Imports by adding @importFrom in some
> documentation.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/christianparobek/skeleSim/issues/55#issuecomment-221407056

## 

Allan Strand,   Biology    http://linum.cofc.edu
College of Charleston      Ph. (843) 953-9189
Charleston, SC 29424     Fax (843) 953-9199

**Comment by EricArcher** [comment]
Got it. I've added an @import directive for markdown and shinyFiles in the runSim documentation.
It now passes the check regarding importing. We still get a NOTE about importing too many packages in Depends that the CRAN guards may give us some grief on:

```
checking package dependencies ... NOTE
Depends: includes the non-default packages:
  ‘strataG’ ‘rmetasim’ ‘shiny’ ‘shinyFiles’ ‘markdown’ ‘ggplot2’
Adding so many packages to the search path is excessive and importing
selectively is preferable.
```

 With a bit of work, we could probably selectively import from rmetasim, strataG, and ggplot2. I'll get started on this in the hopes that just having shiny, shinyFiles, and markdown in the Depends list will be kosher.
